### ISSUE TITLE
How to use your stuff ?

### ISSUE THREAD

**Issue by joublie** [nicuveo/HCM#1]
Hello, I just wanted to try your code, but I don't know Haskell, and even though I tried, I failed to use your code, getting some errors:

>G:\Data\Scripts\HCM\HCM>runhaskell Setup.hs configure
>Configuring HCM-0.1.0...
>Setup.hs: Encountered missing dependencies:
>MissingH -any,
>aeson -any,
>ansi-terminal -any,
>http-conduit -any,
>ixset -any,
>tabular -any,
>text-format -any,
>url -any

or even:

>G:\Data\Scripts\HCM\HCM\src>runhaskell Main.hs
>
>Card.hs:36:1: error:
>    Failed to load interface for `Data.Aeson'
>    Perhaps you meant Data.Version (from base-4.9.1.0)
>    Use -v to see a list of the files searched for.
>
>Card.hs:37:1: error:
>    Failed to load interface for `Data.Aeson.Types'
>    Use -v to see a list of the files searched for.
>
>Card.hs:40:1: error:
>    Failed to load interface for `Data.IxSet'
>    Perhaps you meant
>      Data.IntSet (from containers-0.5.7.1)
>      Data.Set (from containers-0.5.7.1)
>      Data.IORef (from base-4.9.1.0)
>    Use -v to see a list of the files searched for.

How do you set things up, and run your code ?

Thanks.

**Comment by joublie** [comment]
Ok, I found out how to build it, then I was able to run it.

Building, from the main HCM directory, where the Setup.hs file stands:

> stack build

Then I ran it from the directory where it was built.

I'll look into adding Journey to Un-goro extension, let me know if you have some advice about this ;)

Thanks.

**Comment by nicuveo** [comment]
Hey! Sorry it took me so long to answer you. You're my first user! :)
I'm working on adding Un'Goro and fixing a few things; here's a short list of things I'm working on:

UI:
  * fix the "missing" filter (it considers that you're missing one Legendary card if you only have one)
  * fix the help menu to show all filters

Backend:
  * fix the "local database" format to easily support new versions of the code / the program without having to manually migrate the database...
  * fix the input process to save after each card (so that your progress is saved even if you quit mid input)

Let me know if you have more requests / if you found some other bugs!

**Comment by joublie** [comment]
Thanks a lot for getting back to me ^^

I was wondering: some tools like Innkeeper from Hearthpwn are able to discover cards I have directly from the game, so would it be possible for you to implement the same thing in HCM ?

**Comment by nicuveo** [comment]
I wanted to look into that; I can't promise I'll have the time though. ^^

**Comment by nicuveo** [comment]
I pushed an update to the dev branch: it fixes most of the problems I've mentioned and adds support for Un'Goro; let me know if you encounter any issue with it!

**Comment by nicuveo** [comment]
Oh, and to answer your original question: `stack install` is the way to go; you can use the hcm binary from wherever you want after that. Your data directory is ~/.hcm under Linux, and C:/Users/_username_/AppData/Roaming/hcm under Windows; hopefully you won't need to care about that. :)
